{"event": "verbose", "uuid": "fefe3186-807d-4bc0-bd21-4c57ec3b8595", "counter": 11, "stdout": "\u001b[0;31mThe error appears to be in '/home/dpupo/ansible-runner/project/test.yml': line 4, column 7, but may\u001b[0m", "start_line": 10, "end_line": 11, "runner_ident": "14d7ef7f-f7c1-4c25-b844-eeb88fc4c027", "created": "2021-10-08T20:51:11.863212"}